### ISSUE TITLE
Unwanted files

### ISSUE THREAD

**Issue by spikyian** [MERG-DEV/CBUSlib#2]
The commit b07b673ee6d5e13f6762bb720c62c370761f784b contains application specific files. Can you please check if these are really needed.

**Comment by spikyian** [comment]
Perhaps the module specific files should be put into a subdirectory so that the root of the repo contains just the core files?

**Comment by pnbgit** [comment]
Could you let me know which files you think are module specific?

**Comment by spikyian** [comment]
When I created the XC8 branch I was surprised by:

- analogue.[ch]
- canmio.asm
- canmio1.0.asm
- chkinp,asm
- mioSLiM.c 

At the moment I think if I were to just point MPLAB at the library and the CANMIO configurable repo then I would end up with unnecessary globals being included.

I think having this type of 'application may want to use this' source is very useful but need to consider how a user of the library will use these files - particularly if they are making enhancements to the library as currently if they delete the files that don't apply and then push their enhancements then the files chold be removed from master.

**Comment by spikyian** [comment]
Maybe it is a matter of telling MPLAB which files to selectively include in the project rather than deleting the unneeded ones?

Someone creating a new module would do:

1. create a new repo in Github for their module
2. and clone this new repo, CANnone, and CBUSlib onto their development machine.
3. copy files from CANnone to their module's local repo, renaming files as necessary.
4. Then create an MPLAB project 
5. "Import Existing Items from Directory" from their module's local git repo
6. Selectively "Import Existing Item" from the CBUSlib local repo
7. changes can then be committed and pushed upstream to their module's github repo and also to CBUSlib without fear of removing the unincluded files.

People that are not Owners may need to do a fork into their personal Githib repos.
